name: Export Qinglong Image

on:
  workflow_dispatch: # 允许手动触发

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Qinglong Image
        run: docker pull whyour/qinglong:latest

      - name: Save Image to Tar
        run: docker save -o qinglong.tar whyour/qinglong:latest

      - name: Upload Tar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: qinglong-image
          path: qinglong.tar
          retention-days: 7 # 保留7天
